# Generated by Django 4.1 on 2022-12-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_property_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='files/')),
                ('property_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.property')),
            ],
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
