# Generated by Django 4.1 on 2023-04-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sell',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
